export const languagesMap = {
    en: "English",
    fr: "French",
    es: "Spanish",
    de: "German",
    it: "Italian",
    pt: "Portuguese",
    nl: "Dutch",
    pl: "Polish",
    ro: "Romanian",
    tr: "Turkish",
    ja: "Japanese",
    zh: "Chinese",
    ar: "Arabic",
    he: "Hebrew",
    hi: "Hindi",
    id: "Indonesian",
    ms: "Malay",
    th: "Thai",
    vi: "Vietnamese",
};